%% Import prediction from Weka.
% Script for importing data from the following text file:
%
%    /Users/minseokie/Desktop/Project/only10/alltest10
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/05/17 20:08:31

%% Initialize variables.
filename = '/Users/minseokie/Desktop/Project/1to4test/test5to10me';
delimiter = {',',' '};
startRow = 7467; %%7647 %%7501 %%7467
endRow = 8162; %%9362 %%8700 %%8666

%% Format for each line of text:
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'EmptyValue', NaN, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
predictWeka = table(dataArray{1:end-1}, 'VariableNames', {'information'});

%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;