% %% run 

addData('aerk');
addData('ant');
addData('aof');
addData('army');
addData('fasai');
addData('men');
addData('noon');
addData('tum');
addData('yung');
addData('miewy');
addData('neary');
addData('nony');
addData('boongy');
addData('minniey');
addData('puiy');
addData('louisy');
addData('minty');
%
addData('aerk2');
addData('ant2');
addData('aof2');
addData('army2');
addData('fasai2');
addData('louis2');
addData('men2');
addData('noon2');
addData('tum2');
addData('yung2');
addData('miew2y');
addData('near2y');
addData('pepper2y');
addData('pui2y');

%
addData('ant3');
addData('aof3');
addData('army3');
addData('fasai3');
addData('men3');
addData('near3');
addData('noon3');
addData('pui3');
addData('yung3');
%%
addData('ant4');
addData('aof4');
addData('army4');
addData('fasai4');
addData('men4');
addData('near4');
addData('noon4');
addData('pui4');
addData('tum4');
addData('yung4');
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
addData('ant5');
addData('aof5');
addData('fasai5');
addData('pui5');

%%
addData('ant6');
addData('aof6');
addData('fasai6');
addData('pui6');
addData('tum6');
% %%
addData('ant7');
addData('aof7');
addData('fasai7');
addData('pui7');
addData('tum7');
%%
addData('ant8');
addData('aof8');
addData('fasai8');
addData('pui8');
addData('tum8');
%%
addData('ant9');
addData('aof9');
addData('fasai9');
addData('pui9');
addData('tum9');
%%
addData('ant10');
addData('aof10');
addData('fasai10');
addData('pui10');
addData('tum10');

